<template>
  <transition
    name="message-fade"
    @before-leave="onClose"
    @after-leave="$emit('destroy')"
  >
    <div
      v-show="visible"
      :style="customStyle"
      :class="[
        'message',
        type ? `${type}` : '',
        customClass,
        center ? 'is-center' : '',
        showClose ? 'is-closetab' : '',
      ]"
      @mouseenter="clearTimer"
      @mouseleave="startTimer"
    >
      <IconFont v-if="type === 'warning'" type="icon-Alert2" :class="[typeClass, 'message__icon']" />
      <IconFont v-if="type === 'success'" type="icon-Check" :class="[typeClass, 'message__icon']" />
      <IconFont v-if="type === 'error'" type="icon-Alert" :class="[typeClass, 'message__icon']" />
      <IconFont v-if="type === 'info'" type="icon-Info" :class="[typeClass, 'message__icon']" />
      <i v-if="type === 'loading'" :class="[typeClass, 'message__icon']">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          style="
            margin: auto;
            background: rgb(255, 255, 255);
            display: block;
            shape-rendering: auto;
          "
          width="20px"
          height="20px"
          viewBox="0 0 100 100"
          preserveAspectRatio="xMidYMid"
        >
          <circle
            cx="50"
            cy="50"
            fill="none"
            stroke="#8f7ef4"
            stroke-width="10"
            r="35"
            stroke-dasharray="164.93361431346415 56.97787143782138"
          >
            <animateTransform
              attributeName="transform"
              type="rotate"
              repeatCount="indefinite"
              dur="1s"
              values="0 50 50;360 50 50"
              keyTimes="0;1"
            />
          </circle>
          <!-- [ldio] generated by https://loading.io/ -->
        </svg>
      </i>
      <slot>
        <p v-if="!dangerouslyUseHTMLString" class="message__content">
          {{ message }}
        </p>
        <p v-else class="message__content" v-html="message"></p>
      </slot>
      <div
        v-if="showClose"
        class="message__closeBtn icon-close"
        @click.stop="close"
        style="cursor:pointer"
      >
        <svg
          t="1647861317172"
          viewBox="0 0 1024 1024"
          version="1.1"
          xmlns="http://www.w3.org/2000/svg"
          p-id="7170"
          width="16"
          height="16"
        >
          <path
            d="M342.656 297.344a32 32 0 1 0-45.312 45.312L466.752 512l-169.408 169.344a32 32 0 0 0 45.312 45.312L512 557.248l169.344 169.408a32 32 0 0 0 45.312-45.312L557.248 512l169.408-169.344a32 32 0 0 0-45.312-45.312L512 466.752 342.656 297.344z"
            fill="#282C4A"
            p-id="7171"
          ></path>
        </svg>
      </div>
    </div>
  </transition>
</template>

<script>
import IconFont from "../../iconFont";
import {
  defineComponent,
  computed,
  onBeforeUnmount,
  onMounted,
  ref,
} from "vue";
import { on, off } from "./utils/dom";

const typeMap = {
  success: "success",
  info: "info",
  warning: "warning",
  error: "error",
  waiting: "waiting",
};

export default defineComponent({
  name: "message",
  components: {
    IconFont,
  },
  props: {
    customClass: { type: String, default: "" },
    center: { type: Boolean, default: false },
    dangerouslyUseHTMLString: { type: Boolean, default: false },
    duration: { type: Number, default: 3000},
    id: { type: String, default: "" },
    message: { type: [String, Object], default: "" },
    onClose: { type: Function, require: true },
    showClose: { tyep: Boolean, default: false },
    type: { type: String, default: "info" },
    offset: { type: Number, default: 80 },
    zIndex: { type: Number, default: 1001 },
  },
  emits: ["destroy"],
  setup(props) {
    const typeClass = computed(() => {
      const type = props.type;
      return type && typeMap[type] ? `icon-${typeMap[type]}` : "";
    });

    const customStyle = computed(() => {
      return {
        top: `${props.offset}px`,
        zIndex: props.zIndex,
      };
    });

    const visible = ref(false);
    let timer = null;
    function startTimer() {
      if (props.duration > 0) {
        timer = setTimeout(() => {
          if (visible.value) {
            close();
          }
        }, props.duration);
      }
    }
    function clearTimer() {
      clearTimeout(timer);
      timer = null;
    }
    function close() {
      visible.value = false;
    }
    function keydown({ code }) {
      if (code === "Escape") {
        if (visible.value) {
          close();
        }
      } else {
        startTimer();
      }
    }

    onMounted(() => {
      startTimer();
      visible.value = true;
      on(document, "keydown", keydown);
    });

    onBeforeUnmount(() => {
      off(document, "keydown", keydown);
    });

    return {
      customStyle,
      typeClass,
      visible,
      close,
      startTimer,
      clearTimer,
    };
  },
});
</script>

<style lang="scss" scoped>
.message {
  box-sizing: border-box;
  border-radius: 4px;
  position: fixed;
  left: 50%;
  transform: translateX(-50%);
  background-color: #ffffff;
  transition: opacity 0.3s, transform 0.4s, top 0.4s;
  overflow: hidden;
  padding: 12px 16px;
  display: flex;
  align-items: center;
  z-index: 1001 !important;
  box-shadow: 0px 0px 30px 5px rgba(0, 0, 0, 0.1),
    0px 8px 10px -5px rgba(0, 0, 0, 0.08);
  border-radius: 4px;
  flex-direction: row;
  text-align: center;
  p {
    position: static;
    height: 22px;
    left: 32px;
    top: calc(50% - 22px / 2);
    /* Headline 4 - Regular */
    font-family: "Noto Sans SC";
    font-style: normal;
    font-weight: 400;
    font-size: 14px;
    line-height: 22px;
    /* identical to box height, or 157% */
    color: rgba(40, 44, 74, 0.6);
    /* Inside auto layout */
    flex: none;
    order: 1;
    flex-grow: 0;
  }
  &.is-center {
    justify-content: center;
  }
  &.closetab &__content {
    padding-right: 16px;
  }
  &__content {
    padding: 0;
    font-size: 14px;
    line-height: 1;
    &:focus {
      outline-width: 0;
    }
  }
  &__closeBtn {
    /* icon16px-delete2 */
    position: static;
    /* Inside auto layout */
    flex: none;
    order: 1;
    margin: 0px 0px 0px 24px;
    &:focus {
      outline-width: 0;
    }
    &:hover {
      color: #909399;
    }
  }
  &__icon {
    margin-right: 8px;
    font-size: 24px;
  }
}

.message-fade-enter-active,
.message-fade-leave-active {
  opacity: 0;
  transform: translate(-50%, -100%);
}
</style>
